export const RS_CITIES = [
  "Porto Alegre",
  "Caxias do Sul",
  "Pelotas",
  "Santa Maria",
  "Canoas",
  "Gravataí",
  "Viamão",
  "Novo Hamburgo",
  "São Leopoldo",
  "Alvorada",
  "Sapucaia do Sul",
  "Esteio",
  "Cachoeirinha",
  "Guaíba",
  "Arroio dos Ratos",
  "Camaquã",
  "Charqueadas",
  "Triunfo",
  "Eldorado do Sul",
  "Arambaré",
  "Arroio Grande",
  "Jaguarão",
  "Rio Grande",
  "Santa Vitória do Palmar",
  "Santana do Livramento",
  "Bagé",
  "Caçapava do Sul",
  "Lavras do Sul",
  "Piratini",
  "Rosário do Sul",
  "Santana da Boa Vista",
  "São Gabriel",
  "Aceguá",
  "Maçambá",
  "Hulha Negra",
  "Herval",
  "Canguçu",
  "Morro Redondo",
  "Pinheiro Machado",
  "Cerrito",
  "Encruzilhada do Sul",
  "Tubarão",
  "Camboim",
  "Bom Jardim da Serra",
  "Vacaria",
  "Esmeralda",
  "Muitos Córregos",
  "Lagoa Vermelha",
  "Serafina Corrêa",
  "Getúlio Vargas",
  "Soledade",
  "Passo Fundo",
  "Marau",
  "Chapada",
  "Ibiraiaras",
  "Ernestina",
  "Ciríaco",
  "Mato Castelhano",
  "Pontão",
  "Sertão",
  "Tapejara",
  "Sarandi",
  "Erechim",
  "Maximiliano de Almeida",
  "Barracão",
  "Itatiba do Sul",
  "Marcelino Ramos",
  "Viadutos",
  "Cruzeiro do Sul",
  "Três Arroios",
  "Telêmaco Borba",
  "Carazinho",
  "Não-Me-Toque",
  "Barão de Cotegipe",
  "Jóia",
  "Tio Hugo",
  "Selbach",
  "Ajuricaba",
  "Panambi",
  "Ronda Alta",
  "Rondinha",
  "Espumoso",
  "Araçatuba",
  "Arroio do Meio",
  "Arvorezinha",
  "Anta Gorda",
  "Ilópolis",
  "Imigrante",
  "Poço das Antas",
  "Bom Jesus",
  "Farroupilha",
  "Flores da Cunha",
  "Garibaldi",
  "Nova Pádua",
  "Protásio Alves",
  "São Marcos",
  "Veranópolis",
  "Fagundes Varela",
  "Pinto Bandeira",
  "Guaporé",
  "Montauri",
  "Nova Araçá",
  "Roca Sales",
  "Travesseiro",
  "Bento Gonçalves",
  "Gramado",
  "Canela",
  "Três Coroas",
  "Três Forquilhas",
  "Taquara",
  "Riozinho",
  "Rolante",
  "Parobé",
  "Igrejinha",
  "Estância Velha"
].sort();