
import { createRequire } from 'module';
import path from 'path';
import { fileURLToPath } from 'url';

const require = createRequire(import.meta.url);
const XLSX = require('xlsx');

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const filePath = path.join('C:', 'Users', 'Usuario', 'Desktop', 'CAOCIPP', 'Municípios do RS.xlsx');

try {
    const workbook = XLSX.readFile(filePath);
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];

    // Get all data as JSON (array of arrays)
    const data = XLSX.utils.sheet_to_json(worksheet, { header: 1 });

    // Flatten and clean up
    // Assuming the list is just a column of names.
    // We filter out header 'Município' if present.
    const cities = data
        .flat()
        .filter(c => c && typeof c === 'string' && c.trim() !== '' && c.toLowerCase().trim() !== 'município')
        .map(c => c.trim())
        .sort((a, b) => a.localeCompare(b));

    const outputPath = path.join('C:', 'Users', 'Usuario', 'Desktop', 'CAOCIPP', 'src', 'utils', 'cities.js');

    const fileContent = `// Automatically generated by scripts/extract_cities.js
export const RS_CITIES = ${JSON.stringify(cities, null, 2)};
`;

    const fs = require('fs');
    fs.writeFileSync(outputPath, fileContent, 'utf8');

    console.log(`Successfully wrote ${cities.length} cities to ${outputPath}`);

} catch (error) {
    console.error("Error reading file:", error);
}
